services:
  nuxt-app:
    container_name: app
    image: ghcr.io/ilyamoraru/pokerplanning:latest
    #    image: nuxt-docker
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      NUXT_PUBLIC_API_BASE_URL: http://185.185.71.82:8080
    networks:
      - poker-frontend
    #    restart: on-failure:5
    restart: always

networks:
  poker-frontend:
    driver: bridge
